export const authTypes = {
  LOGIN_REQUEST: 'USERS_LOGIN_REQUEST',
  LOGIN_SUCCESS: 'USERS_LOGIN_SUCCESS',
  LOGIN_FAILURE: 'USERS_LOGIN_FAILURE'
};
export const dashboardTypes = {
  GET_DASHBOARD_REQUEST: 'GET_DASHBOARD_REQUEST',
  GET_DASHBOARD_FAILURE: 'GET_DASHBOARD_FAILURE'
};
export const venueTypes = {
  VENUES: {
    SYNC: 'VENUES.SYNC'
  },
  GET_VENUES_REQUEST: 'GET_VENUES_REQUEST',
  GET_VENUES_SUCCESS: 'GET_VENUES_SUCCESS',
  GET_VENUES_FAILURE: 'GET_VENUES_FAILURE'
};

export const userTypes = {
  LOGIN_WITH_TOKEN: 'LOGIN_WITH_TOKEN',
  USERS: { SYNC: 'USERS.SYNC' },
  USER: { SYNC: 'USER.SYNC' },
  GET_USERS_REQUEST: 'GET_USERS_REQUEST',
  GET_USERS_SUCCESS: 'GET_USERS_SUCCESS',
  GET_USERS_FAILURE: 'GET_USERS_FAILURE',
  SET_SORT_KEY: 'SET_SORT_KEY',
  SELECT_ALL_USERS: 'SELECT_ALL_USERS',
  UNSELECT_ALL_USERS: 'UNSELECT_ALL_USERS',
  SELECT_SINGLE_USER: 'SELECT_SINGLE_USER',
  UNSELECT_SINGLE_USER: 'UNSELECT_SINGLE_USER'
};

export const configTypes = {
  CONFIG: {
    SYNC: 'CONFIG.SYNC'
  },
  GET_CONFIG_REQUEST: 'GET_CONFIG_REQUEST',
  GET_CONFIG_SUCCESS: 'GET_CONFIG_SUCCESS',
  GET_CONFIG_FAILURE: 'GET_CONFIG_FAILURE'
};

export const eventTypes = {
  EVENTS: {
    SYNC: 'EVENTS.SYNC'
  },
  GET_EVENTS_REQUEST: 'GET_EVENTS_REQUEST',
  GET_EVENTS_SUCCESS: 'GET_EVENTS_SUCCESS',
  GET_EVENTS_FAILURE: 'GET_EVENTS_FAILURE',

  SET_SORT_KEY: 'SET_SORT_KEY',
  SET_ADD_EMPLOYEE_OPEN: 'SET_ADD_EMPLOYEE_OPEN'
};

export const alertTypes = {
  SUCCESS: 'ALERT_SUCCESS',
  ERROR: 'ALERT_ERROR',
  CLEAR: 'ALERT_CLEAR'
};

export const billingTypes = {
  INCREMENT_MONTH: 'INCREMENT_MONTH',
  DECREMENT_MONTH: 'DECREMENT_MONTH',
};
