export const authTypes = {
  LOGIN_REQUEST: 'USERS_LOGIN_REQUEST',
  LOGIN_SUCCESS: 'USERS_LOGIN_SUCCESS',
  LOGIN_FAILURE: 'USERS_LOGIN_FAILURE',

  GET_CURRENT_USER_REQUEST: 'GET_CURRENT_USER_REQUEST',
  GET_CURRENT_USER_SUCCESS: 'GET_CURRENT_USER_SUCCESS',
  GET_CURRENT_USER_FAILURE: 'GET_CURRENT_USER_FAILURE',

  GO_BACK_HOME_REQUEST: 'GO_BACK_HOME_REQUEST',
  GO_BACK_HOME_SUCCESS: 'GO_BACK_HOME_SUCCESS',
  GO_BACK_HOME_FAILURE: 'GO_BACK_HOME_FAILURE',

  POST_REFRESH_SESSION_REQUEST: 'POST_REFRESH_SESSION_REQUEST',
  POST_REFRESH_SESSION_SUCCESS: 'POST_REFRESH_SESSION_SUCCESS',
  POST_REFRESH_SESSION_FAILURE: 'POST_REFRESH_SESSION_FAILURE'
};
